### ISSUE TITLE
New firmware versions are available

### ISSUE THREAD

**Issue by Rocky04** [CommunityGD32Cores/gigadevice-firmware-and-docs#2]
There are [new firmware versions available ](http://www.gd32mcu.com/en/download/7)for multiple device families.

- [GD32F4xx (3.0.0)](http://www.gd32mcu.com/download/down/document_id/247/path_type/1)
- [GD32F3x0 (2.2.0)](http://www.gd32mcu.com/download/down/document_id/143/path_type/1)
- [GD32F30x (2.1.3)](http://www.gd32mcu.com/download/down/document_id/129/path_type/1)
- [GD32F20x (2.3.1)](http://www.gd32mcu.com/download/down/document_id/194/path_type/1)
- [GD32E50x (1.2.2)](http://www.gd32mcu.com/download/down/document_id/282/path_type/1)
- [GD32F10x (2.2.2)](http://www.gd32mcu.com/download/down/document_id/180/path_type/1)
- [GD32VF103 (1.1.3)](http://www.gd32mcu.com/download/down/document_id/266/path_type/1)
- [GD32F1x0 (3.3.3)](http://www.gd32mcu.com/download/down/document_id/288/path_type/1)
- [GD32E23x (1.1.2)](http://www.gd32mcu.com/download/down/document_id/216/path_type/1)
- [GD32L23x (1.0.1)](http://www.gd32mcu.com/download/down/document_id/290/path_type/1)

_By the way, for some families the "AddOn" package is archived while for other not. So there is an inconsistency._

**Comment by obra** [comment]
Thanks!  I've grabbed all of these. If you see anything else we're missing, please don't hesitate to let us know.

Fixes #2
